\set ON_ERROR_STOP on
BEGIN;
SET client_min_messages TO WARNING;
\copy ADMISSIONS (ROW_ID, SUBJECT_ID, HADM_ID, ADMITTIME, DISCHTIME, ADMISSION_TYPE, ADMISSION_LOCATION, DISCHARGE_LOCATION, INSURANCE, LANGUAGE, MARITAL_STATUS, ETHNICITY, AGE) FROM '/tmp/ehrsql_import/mimic_iii/csv/ADMISSIONS.csv' WITH (FORMAT csv, NULL '\N')
\copy CHARTEVENTS (ROW_ID, SUBJECT_ID, HADM_ID, ICUSTAY_ID, ITEMID, CHARTTIME, VALUENUM, VALUEUOM) FROM '/tmp/ehrsql_import/mimic_iii/csv/CHARTEVENTS.csv' WITH (FORMAT csv, NULL '\N')
\copy COST (ROW_ID, SUBJECT_ID, HADM_ID, EVENT_TYPE, EVENT_ID, CHARGETIME, COST) FROM '/tmp/ehrsql_import/mimic_iii/csv/COST.csv' WITH (FORMAT csv, NULL '\N')
\copy DIAGNOSES_ICD (ROW_ID, SUBJECT_ID, HADM_ID, ICD9_CODE, CHARTTIME) FROM '/tmp/ehrsql_import/mimic_iii/csv/DIAGNOSES_ICD.csv' WITH (FORMAT csv, NULL '\N')
\copy D_ICD_DIAGNOSES (ROW_ID, ICD9_CODE, SHORT_TITLE, LONG_TITLE) FROM '/tmp/ehrsql_import/mimic_iii/csv/D_ICD_DIAGNOSES.csv' WITH (FORMAT csv, NULL '\N')
\copy D_ICD_PROCEDURES (ROW_ID, ICD9_CODE, SHORT_TITLE, LONG_TITLE) FROM '/tmp/ehrsql_import/mimic_iii/csv/D_ICD_PROCEDURES.csv' WITH (FORMAT csv, NULL '\N')
\copy D_ITEMS (ROW_ID, ITEMID, LABEL, LINKSTO) FROM '/tmp/ehrsql_import/mimic_iii/csv/D_ITEMS.csv' WITH (FORMAT csv, NULL '\N')
\copy D_LABITEMS (ROW_ID, ITEMID, LABEL) FROM '/tmp/ehrsql_import/mimic_iii/csv/D_LABITEMS.csv' WITH (FORMAT csv, NULL '\N')
\copy ICUSTAYS (ROW_ID, SUBJECT_ID, HADM_ID, ICUSTAY_ID, FIRST_CAREUNIT, LAST_CAREUNIT, FIRST_WARDID, LAST_WARDID, INTIME, OUTTIME) FROM '/tmp/ehrsql_import/mimic_iii/csv/ICUSTAYS.csv' WITH (FORMAT csv, NULL '\N')
\copy INPUTEVENTS_CV (ROW_ID, SUBJECT_ID, HADM_ID, ICUSTAY_ID, CHARTTIME, ITEMID, AMOUNT) FROM '/tmp/ehrsql_import/mimic_iii/csv/INPUTEVENTS_CV.csv' WITH (FORMAT csv, NULL '\N')
\copy LABEVENTS (ROW_ID, SUBJECT_ID, HADM_ID, ITEMID, CHARTTIME, VALUENUM, VALUEUOM) FROM '/tmp/ehrsql_import/mimic_iii/csv/LABEVENTS.csv' WITH (FORMAT csv, NULL '\N')
\copy MICROBIOLOGYEVENTS (ROW_ID, SUBJECT_ID, HADM_ID, CHARTTIME, SPEC_TYPE_DESC, ORG_NAME) FROM '/tmp/ehrsql_import/mimic_iii/csv/MICROBIOLOGYEVENTS.csv' WITH (FORMAT csv, NULL '\N')
\copy OUTPUTEVENTS (ROW_ID, SUBJECT_ID, HADM_ID, ICUSTAY_ID, CHARTTIME, ITEMID, VALUE) FROM '/tmp/ehrsql_import/mimic_iii/csv/OUTPUTEVENTS.csv' WITH (FORMAT csv, NULL '\N')
\copy PATIENTS (ROW_ID, SUBJECT_ID, GENDER, DOB, DOD) FROM '/tmp/ehrsql_import/mimic_iii/csv/PATIENTS.csv' WITH (FORMAT csv, NULL '\N')
\copy PRESCRIPTIONS (ROW_ID, SUBJECT_ID, HADM_ID, STARTDATE, ENDDATE, DRUG, DOSE_VAL_RX, DOSE_UNIT_RX, ROUTE) FROM '/tmp/ehrsql_import/mimic_iii/csv/PRESCRIPTIONS.csv' WITH (FORMAT csv, NULL '\N')
\copy PROCEDURES_ICD (ROW_ID, SUBJECT_ID, HADM_ID, ICD9_CODE, CHARTTIME) FROM '/tmp/ehrsql_import/mimic_iii/csv/PROCEDURES_ICD.csv' WITH (FORMAT csv, NULL '\N')
\copy TRANSFERS (ROW_ID, SUBJECT_ID, HADM_ID, ICUSTAY_ID, EVENTTYPE, CAREUNIT, WARDID, INTIME, OUTTIME) FROM '/tmp/ehrsql_import/mimic_iii/csv/TRANSFERS.csv' WITH (FORMAT csv, NULL '\N')
COMMIT;
